Feature: The Order service back-end # features/orders.feature:1
  As a Order Manager
  I need a RESTful order service
  So that I can keep track of all orders
  Background:   # features/orders.feature:6

  Scenario: The server is running                               # features/orders.feature:17
    Given the following orders                                  # features/steps/order_steps.py:40
      | customer_id | order_date | status   | shipping_address | total_amount | payment_method | shipping_cost | expected_date | order_notes   |
      | 123         | 2022-06-16 | STARTED  | fake address     | 1            | CREDIT         | 10            | 2022-06-20    | Some notes    |
      | 456         | 2022-07-01 | SHIPPING | real address     | 100.50       | DEBIT          | 5.99          | 2022-07-05    | Special notes |
    Given the following items                                   # features/steps/order_steps.py:70
      | product_id | name   | quantity | unit_price | total_price |
      | 25         | Phone  | 2        | 1000       | 2000        |
      | 30         | laptop | 1        | 6000       | 6000        |
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/order_steps.py", line 90, in step_impl
          assert context.resp.status_code == HTTP_201_CREATED
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AssertionError

    When I visit the "Home Page"                                # None
    Then I should see "Order Demo RESTful Service" in the title # None
    And I should not see "404 Not Found"                        # None

  Scenario: Create an Order                                             # features/orders.feature:22
    Given the following orders                                          # features/steps/order_steps.py:40
      | customer_id | order_date | status   | shipping_address | total_amount | payment_method | shipping_cost | expected_date | order_notes   |
      | 123         | 2022-06-16 | STARTED  | fake address     | 1            | CREDIT         | 10            | 2022-06-20    | Some notes    |
      | 456         | 2022-07-01 | SHIPPING | real address     | 100.50       | DEBIT          | 5.99          | 2022-07-05    | Special notes |
    Given the following items                                           # features/steps/order_steps.py:70
      | id   | order_id | product_id | name   | quantity | unit_price | total_price |
      | 4098 | 8782     | 25         | Phone  | 2        | 1000       | 2000        |
      | 4099 | 8782     | 30         | laptop | 1        | 6000       | 6000        |
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/order_steps.py", line 90, in step_impl
          assert context.resp.status_code == HTTP_201_CREATED
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AssertionError

    When I visit the "Home Page"                                        # None
    And I set the "Customer ID" to "1234"                               # None
    And I set the "Order Date" to "06-15-2022"                          # None
    And I set the "Status" to "Started"                                 # None
    And I set the "Shipping Address" to "fakefake address"              # None
    And I set the "Total Amount" to "2"                                 # None
    And I set the "Payment Method" to "CREDIT"                          # None
    And I set the "Shipping Cost" to "20"                               # None
    And I set the "Expected Date" to "06-22-2022"                       # None
    And I set the "Order Notes" to "None"                               # None
    And I press the "Create" button                                     # None
    Then I should see the message "Success"                             # None
    And I save the "Order Id" field as "order_id"                       # None
    When I copy the "Order Id" field                                    # None
    And I press the "Retrieve" button                                   # None
    Then I should see the message "Success"                             # None
    And I should see "1234" in the "Customer ID" field                  # None
    And I should see "2022-06-15" in the "Order Date" field             # None
    And I should see "STARTED" in the "Status" field                    # None
    And I should see "fakefake address" in the "Shipping Address" field # None
    And I should see "2" in the "Total Amount" field                    # None
    And I should see "CREDIT" in the "Payment Method" field             # None
    And I should see "20" in the "Shipping Cost" field                  # None
    And I should see "2022-06-22" in the "Expected Date" field          # None
    And I should see "None" in the "Order Notes" field                  # None

  Scenario: Create an Item                                                     # features/orders.feature:50
    Given the following orders                                                 # features/steps/order_steps.py:40
      | customer_id | order_date | status   | shipping_address | total_amount | payment_method | shipping_cost | expected_date | order_notes   |
      | 123         | 2022-06-16 | STARTED  | fake address     | 1            | CREDIT         | 10            | 2022-06-20    | Some notes    |
      | 456         | 2022-07-01 | SHIPPING | real address     | 100.50       | DEBIT          | 5.99          | 2022-07-05    | Special notes |
    Given the following items                                                  # features/steps/order_steps.py:70
      | id   | order_id | product_id | name   | quantity | unit_price | total_price |
      | 4098 | 8782     | 25         | Phone  | 2        | 1000       | 2000        |
      | 4099 | 8782     | 30         | laptop | 1        | 6000       | 6000        |
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/order_steps.py", line 90, in step_impl
          assert context.resp.status_code == HTTP_201_CREATED
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AssertionError

    When I visit the "Home Page"                                               # None
    And I set the "Item Order ID" to "{order_id}"                              # None
    And I set the "Product ID" to "100"                                        # None
    And I set the "Name" to "Ruler"                                            # None
    And I set the "Quantity" to "10"                                           # None
    And I set the "Unit Price" to "29.99"                                      # None
    And I calculate and set the "Total Price" based on quantity and unit price # None
    And I set the "Description" to "None"                                      # None
    And I press the "Create Item" button                                       # None
    Then I should see the message "Success"                                    # None
    When I copy the "Item ID" field                                            # None
    And I press the "Retrieve Item" button                                     # None
    Then I should see the message "Success"                                    # None
    And I should see "100" in the "Product ID" field                           # None
    And I should see "Ruler" in the "Name" field                               # None
    And I should see "10" in the "Quantity" field                              # None
    And I should see "29.99" in the "Unit Price" field                         # None
    And I should see the calculated "Total Price" in the "Total Price" field   # None
    And I should see "None" in the "Description" field                         # None

  Scenario: List all Orders                       # features/orders.feature:71
    Given the following orders                    # features/steps/order_steps.py:40
      | customer_id | order_date | status   | shipping_address | total_amount | payment_method | shipping_cost | expected_date | order_notes   |
      | 123         | 2022-06-16 | STARTED  | fake address     | 1            | CREDIT         | 10            | 2022-06-20    | Some notes    |
      | 456         | 2022-07-01 | SHIPPING | real address     | 100.50       | DEBIT          | 5.99          | 2022-07-05    | Special notes |
    Given the following items                     # features/steps/order_steps.py:70
      | id   | order_id | product_id | name   | quantity | unit_price | total_price |
      | 4098 | 8782     | 25         | Phone  | 2        | 1000       | 2000        |
      | 4099 | 8782     | 30         | laptop | 1        | 6000       | 6000        |
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/order_steps.py", line 90, in step_impl
          assert context.resp.status_code == HTTP_201_CREATED
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AssertionError

    When I visit the "Home Page"                  # None
    And I press the "Clear" button                # None
    And I press the "Search" button               # None
    Then I should see the message "Success"       # None
    And I should see "SHIPPING" in the results    # None
    And I should see "STARTED" in the results     # None
    And I should not see "PACKING" in the results # None

  Scenario: List Items                                     # features/orders.feature:80
    Given the following orders                             # features/steps/order_steps.py:40
      | customer_id | order_date | status   | shipping_address | total_amount | payment_method | shipping_cost | expected_date | order_notes   |
      | 123         | 2022-06-16 | STARTED  | fake address     | 1            | CREDIT         | 10            | 2022-06-20    | Some notes    |
      | 456         | 2022-07-01 | SHIPPING | real address     | 100.50       | DEBIT          | 5.99          | 2022-07-05    | Special notes |
    Given the following items                              # features/steps/order_steps.py:70
      | id   | order_id | product_id | name   | quantity | unit_price | total_price |
      | 4098 | 8782     | 25         | Phone  | 2        | 1000       | 2000        |
      | 4099 | 8782     | 30         | laptop | 1        | 6000       | 6000        |
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/usr/local/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/order_steps.py", line 90, in step_impl
          assert context.resp.status_code == HTTP_201_CREATED
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AssertionError

    When I visit the "Home Page"                           # None
    And I press the "Clear" button                         # None
    And I press the "Search" button                        # None
    Then I should see the message "Success"                # None
    When I press the "Clear Item" button                   # None
    Then the "Item ID" field should be empty               # None
    When I copy the "ID" field                             # None
    And I press the "Clear" button                         # None
    And I paste the "Order ID" field                       # None
    And I press the "Search Item" button                   # None
    Then I should see the message "Success"                # None
    And I should see "Phone" in the "Search Item" results  # None
    And I should see "Laptop" in the "Search Item" results # None


Failing scenarios:
  features/orders.feature:17  The server is running
  features/orders.feature:22  Create an Order
  features/orders.feature:50  Create an Item
  features/orders.feature:71  List all Orders
  features/orders.feature:80  List Items

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 5 failed, 0 skipped
5 steps passed, 5 failed, 67 skipped, 0 undefined
Took 0m0.255s
